# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker run --rm hello-world
  
commerce_build_images:
  stage: build
  script:
    - cd ./net/
    # Install Docker Compose
    - apk add --update py-pip && pip install docker-compose
    - docker-compose -f docker-compose.yml -f docker-compose.override.yml build