# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker run --rm hello-world
after_script:
variables:
cache:
types:
stages:

commerce_build_images:
  stage:build
  script:
    - cd ./net/
    - docker-compose build 
library_unit_test:
commerce_catalog_unit_test:
commerce_integration_test:
commerce_admin_app_unit_test:
commerce_admin_e2e_test: