image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - bash https://dot.net/v1/dotnet-install.sh

commerce_library_unit_test:
  stage: test
  image: microsoft/aspnetcore-build:2.0
  cache:
    untracked: true
    paths:
    - bin/
  script:
    - cd ./net/tests/Enterprise.Library.EventBus.Tests
    - dotnet restore ./Enterprise.Library.EventBus.Tests.csproj
    - dotnet build ./Enterprise.Library.EventBus.Tests.csproj
    - dotnet test ./Enterprise.Library.EventBus.Tests.csproj

commerce_catalog_unit_test:
  stage: test
  image: microsoft/aspnetcore-build:2.0
  cache:
    untracked: true
    paths:
    - bin/
  script:
    - cd ./net/tests/Enterprise.Commerce.Tests
    - docker-compose -f docker-compose-external.yml -f docker-compose-external.override.yml up
    - dotnet restore ./Enterprise.Commerce.Tests.csproj
    - dotnet build ./Enterprise.Commerce.Tests.csproj
    - dotnet test ./Enterprise.Commerce.Tests.csproj

commerce_catalog_integration_test:
  stage: test
  image: microsoft/aspnetcore-build:2.0
  cache:
    untracked: true
    paths:
    - bin/
  script:
    - cd ./net/integration-tests/Enterprise.Commerce.IntegrationTests
    - docker-compose -f docker-compose-external.yml -f docker-compose-external.override.yml up
    - dotnet restore ./Enterprise.Commerce.IntegrationTests.csproj
    - dotnet build ./Enterprise.Commerce.IntegrationTests.csproj
    - dotnet test ./Enterprise.Commerce.IntegrationTests.csproj
