# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  # Install Docker Compose
  - apk add --update py-pip && pip install docker-compose
  

commerce_library_unit_test:
  stage: test
  image: microsoft/aspnetcore-build:2.0
  script:
    - cd ./net/tests/Enterprise.Library.EventBus.Tests
    - dotnet restore ./Enterprise.Library.EventBus.Tests.csproj
    - dotnet build ./Enterprise.Library.EventBus.Tests.csproj
    - dotnet test ./Enterprise.Library.EventBus.Tests.csproj

commerce_catalog_unit_test:
  stage: test
  image: microsoft/aspnetcore-build:2.0
  script:
    - cd ./net/tests/Enterprise.Commerce.Tests
    - docker-compose -f docker-compose-external.yml -f docker-compose-external.override.yml up
    - dotnet restore ./Enterprise.Commerce.Tests.csproj
    - dotnet build ./Enterprise.Commerce.Tests.csproj
    - dotnet test ./Enterprise.Commerce.Tests.csproj
