// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Enterprise.Library.IntegrationEventLog.IntegrationMigrations
{
    [DbContext(typeof(IntegrationEventLogContext))]
    internal class IntegrationEventLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Enterprise.Library.IntegrationEventLog.IntegrationEventLogEntry", b =>
            {
                b.Property<Guid>("EventId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Content")
                    .IsRequired();

                b.Property<DateTime>("CreationTime");

                b.Property<string>("EventTypeName")
                    .IsRequired();

                b.Property<int>("State");

                b.Property<int>("TimesSent");

                b.HasKey("EventId");

                b.ToTable("IntegrationEventLog");
            });
#pragma warning restore 612, 618
        }
    }
}