apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: basket
    spec:
      containers:
      - name: basket
        image: darwinyo/basket.api
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH_BASE
          value: /basket-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: basket__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        # - name: UseLoadTest
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__EnableLoadTest
        # - name: OrchestratorType
        #   value: 'K8S'
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: catalog
    spec:
      containers:
      - name: catalog
        image: darwinyo/catalog.api
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH_BASE
          value: /catalog-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: catalog__ConnectionString
        - name: CategoryImageBaseUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: CategoryImageBaseUrl
        - name: ProductImageBaseUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: ProductImageBaseUrl
        - name: ManufacturerImageBaseUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: ManufacturerImageBaseUrl
        - name: AzureStorageEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: catalog__AzureStorageEnabled
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey
        # - name: OrchestratorType
        #   value: 'K8S' 
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: identity
    spec:
      containers:
      - name: identity
        image: darwinyo/identity.api
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH_BASE
          value: /identity
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: identity__ConnectionString
        - name: DPConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: keystore
        - name: IsClusterEnv
          value: 'True'
        - name: BasketApiClient
          valueFrom:
           configMapKeyRef:
             name: urls
             key: basket_e 
        - name: OrderingApiClient
          valueFrom:
           configMapKeyRef:
             name: urls
             key: order_e
        - name: CatalogApiClient
          valueFrom:
           configMapKeyRef:
             name: urls
             key: catalog_e  
        - name: CommerceClientSpaClient
          valueFrom:
           configMapKeyRef:
             name: urls
             key: commerce-client_e  
        - name: CommerceAdminSpaClient
          valueFrom:
           configMapKeyRef:
             name: urls
             key: commerce-admin_e 
                                             
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey 
        # - name: OrchestratorType
        #   value: 'K8S'                            
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: order
    spec:
      containers:
      - name: order
        image: darwinyo/order.api
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH_BASE
          value: /order-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: order__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        - name: CheckUpdateTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager__CheckUpdateTime
        - name: GracePeriodTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager__GracePeriodTime  
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        # - name: OrchestratorType
        #   value: 'K8S'           
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-backgroundtasks
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: order-backgroundtasks
    spec:
      containers:
      - name: order-backgroundtasks
        image: darwinyo/order.backgroundtasks
        imagePullPolicy: IfNotPresent
        env:        
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: order__ConnectionString
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus        
        - name: CheckUpdateTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager__CheckUpdateTime
        - name: GracePeriodTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager__GracePeriodTime  
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EnableLoadTest
        # - name: OrchestratorType
        #   value: 'K8S'     
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-signalrhub
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: order-signalrhub
    spec:
      containers:
      - name: order-signalrhub
        image: darwinyo/order.signalrhub
        imagePullPolicy: IfNotPresent
        env:                
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus                
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey        
        # - name: OrchestratorType
        #   value: 'K8S'  
        - name: IsClusterEnv
          value: 'True'  
        - name: SignalrStoreConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: keystore 
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: payment
    spec:
      containers:
      - name: payment
        image: darwinyo/payment.api
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH_BASE
          value: /payment-api
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__UseAzureServiceBus
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: all__EventBusConnection
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey
        # - name: OrchestratorType
        #   value: 'K8S'
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key      
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webstatus
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: webstatus
    spec:
      containers:
      - name: webstatus
        image: darwinyo/webstatus
        imagePullPolicy: IfNotPresent
        env:
        - name: PATH_BASE
          value: /webstatus
        - name: BasketUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: basket__hc
        - name: CatalogUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: catalog__hc
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: identity__hc
        - name: OrderingUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: order__hc
        - name: OrderingBackgroundTasksUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: order-background__hc
        - name: PaymentUrl
          valueFrom:
           configMapKeyRef:
             name: internalurls
             key: payment__hc 
        # - name: ApplicationInsights__InstrumentationKey
        #   valueFrom:
        #    configMapKeyRef:
        #      name: externalcfg
        #      key: all__InstrumentationKey  
        # - name: OrchestratorType
        #   value: 'K8S'       
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: commerce-admin
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: commerce-admin
    spec:
      containers:
      - name: commerce-admin
        image: darwinyo/commerce.admin
        imagePullPolicy: IfNotPresent
        env:
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        - name: SignalrUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: order-signalrhub
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: commerce-client
  namespace: enterprise
spec:
  paused: true
  template:
    metadata:
      labels:
        app: enterprise
        component: commerce-client
    spec:
      containers:
      - name: commerce-client
        image: darwinyo/commerce.client
        imagePullPolicy: IfNotPresent
        env:
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: identity_e
        - name: SignalrUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: order-signalrhub

        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: registry-key
---
