apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: keystore-data
  name: keystore-data
  namespace: enterprise
spec:
  ports:
  - port: 6379
  selector:
    app: enterprise
    component: keystore-data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keystore-data
  namespace: enterprise
spec:
  template:
    metadata:
      labels:
        app: enterprise
        component: keystore-data
    spec:
      containers:
      - name: keystore-data
        image: redis

