apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: basket
  name: basket
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: basket
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: catalog
  name: catalog
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: catalog
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: identity
  name: identity
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: identity
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: order
  name: order
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: order
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: order-backgroundtasks
  name: order-background
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: order-backgroundtasks
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: order-signalrhub
  name: order-signalrhub
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: order-signalrhub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: payment
  name: payment
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: payment
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: webstatus
  name: webstatus
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: webstatus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: commerce-admin
  name: commerce-admin
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: commerce-admin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise
    component: commerce-client
  name: commerce-client
  namespace: enterprise
spec:
  ports:
  - port: 80
  selector:
    app: enterprise
    component: commerce-client
