version: '3'

services:
  catalog.api:
    image: darwinyo/catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  sql.data:
    image: localhost:5000/microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: localhost:5000/mongo:3.7.3-jessie

  basket.data:
    image: localhost:5000/redis:alpine
      
  rabbitmq:
    image: localhost:5000/rabbitmq:3.7.4-management-alpine