version: '3'

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Catalog,API/Dockerfile

  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile

