version: '3'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sql.data;Database=Enterprise.Commerce.Services.CatalogDb;User Id=sa;Password=P@ssword}
    ports:
      - "5101:80"

  sql.data:
    environment:
      - SA_PASSWORD=P@ssword
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

  nosql.data:
    ports:
      - "27017:27017"

  basket.data:
    ports:
      - "6379:6379"
      
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

