version: '3'

services:
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo:3.7.3-jessie

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine