apiVersion: v1
kind: PersistentVolume
metadata:
  name: enterprise-jenkins-pv
  namespace: enterprise-jenkins
spec:
  storageClassName: enterprise-jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/