/**
 * Enterprise Commerce - Catalog HTTP API
 * The Catalog Microservice HTTP API. This is a Data-Driven/CRUD microservice sample
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CatalogItemViewModel } from './catalogItemViewModel';

export interface PaginatedCatalogViewModelCatalogItemViewModel {
  pageIndex?: number;
  pageSize?: number;
  count?: number;
  data?: Array<CatalogItemViewModel>;
}
