/**
 * Enterprise Commerce - Catalog HTTP API
 * The Catalog Microservice HTTP API. This is a Data-Driven/CRUD microservice sample
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Manufacturer } from './manufacturer';
import { ProductColor } from './productColor';
import { ProductImage } from './productImage';
import { ProductRating } from './productRating';

export interface Product {
  id?: string;
  name?: string;
  price?: number;
  overallRating?: number;
  totalFavorites?: number;
  totalReviews?: number;
  description?: string;
  lastUpdated?: Date;
  lastUpdatedBy?: string;
  availableStock?: number;
  manufacturerId?: number;
  categoryId?: number;
  timestamp?: string;
  manufacturer?: Manufacturer;
  category?: Category;
  productImages?: Array<ProductImage>;
  productColors?: Array<ProductColor>;
  productRatings?: Array<ProductRating>;
}
