apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  labels:
    app: enterprise  
data:
  basket__ConnectionString: basket-data
  catalog__ConnectionString: Server=sql-data;Initial Catalog=Enterprise.Commerce.Services.CatalogDb;User Id=sa;Password=P@ssw0rd;
  catalog__AzureStorageEnabled: "False"
  identity__ConnectionString: Server=sql-data;Initial Catalog=Enterprise.Commerce.Services.IdentityDb;User Id=sa;Password=P@ssw0rd;
  ordering__ConnectionString: Server=sql-data;Initial Catalog=Enterprise.Commerce.Services.OrderingDb;User Id=sa;Password=P@ssw0rd;
  keystore: keystore-data
  GracePeriodManager__GracePeriodTime: "1"
  GracePeriodManager__CheckUpdateTime: "15000"
  all__EventBusConnection: rabbitmq
  all__InstrumentationKey: ""
  all__EnableLoadTest: "False"
  all__UseAzureServiceBus: "False"



