/**
 * Enterprise Commerce - Catalog HTTP API
 * The Catalog Microservice HTTP API. This is a Data-Driven/CRUD microservice sample
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BasketCheckout {
    buyer?: string;
    requestId?: string;
    city?: string;
    street?: string;
    state?: string;
    country?: string;
    zipCode?: string;
    cardNumber?: string;
    cardHolderName?: string;
    cardExpiration?: Date;
    cardSecurityNumber?: string;
    cardTypeId?: number;
}
