/**
 * Enterprise Commerce - Catalog HTTP API
 * The Catalog Microservice HTTP API. This is a Data-Driven/CRUD microservice sample
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductColor } from './productColor';
import { ProductImage } from './productImage';


export interface ProductViewModel {
    id?: string;
    name?: string;
    price?: number;
    description?: string;
    manufacturerId?: number;
    manufacturerName?: string;
    categoryId?: number;
    categoryName?: string;
    actorId?: string;
    productImages?: Array<ProductImage>;
    productColors?: Array<ProductColor>;
    location?: string;
    minPurchase?: number;
    hasExpiry?: string;
    expireDate?: string;
    discount?: number;
    stock?: number;
}
