version: '3'

services:
  sql.data:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5433:1433"

  nosql.data:
    ports:
      - "27017:27017"

  basket.data:
    ports:
      - "6379:6379"
      
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

