version: '3'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  # nosql.data:
  #   image: mongo:3.7.3-jessie

  # basket.data:
  #   image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine
  
  enterprise.commerce.integrationtests:
    image: enterprise-commerce-integration-tests
    build:
      context: .
      dockerfile: integration-tests/Enterprise.Commerce.IntegrationTests/Dockerfile
    entrypoint: dotnet test
    depends_on:
      - sql.data
      - rabbitmq
    

