version: '3'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo:3.7.3-jessie

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine

  # basket.api:
  #   image: darwinyo/basket.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Commerce/Basket/Basket.API/Dockerfile
  #   depends_on:
  #     - basket.data
  #     - identity.api
  #     - rabbitmq

  catalog.api:
    image: darwinyo/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Commerce/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  # identity.api:
  #   image: darwinyo/identity.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Identity/Identity.API/Dockerfile
  #   depends_on:
  #     - sql.data

  # order.api:
  #   image: darwinyo/order.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Commerce/Order/Order.API/Dockerfile
  #   depends_on:
  #     - sql.data
  #     - rabbitmq

  # order.backgroundtasks:
  #   image: darwinyo/order.backgroundtasks:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Commerce/Order/Order.BackgroundTasks/Dockerfile
  #   depends_on:
  #     - sql.data
  #     - rabbitmq

  # payment.api:
  #   image: darwinyo/payment.api:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/Commerce/Payment/Payment.API/Dockerfile
  #   depends_on:
  #     - rabbitmq   

  # webstatus:
  #   image: darwinyo/webstatus:${TAG:-latest}
  #   build:
  #     context: .
  #     dockerfile: src/HealthCheck/WebStatus/Dockerfile
